# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool: ravinewpool
  #vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
stages:
- stage: create war file
  displayName: war file creation stage
  jobs:
  - job: war file creation
    displayName: Build
    #pool: ravipool
      #vmImage: $(vmImageName)
    steps:
    
- stage: Build
  displayName: Build stage
  jobs:
  - job: Build
    displayName: Build
    #pool: ravipool
      #vmImage: $(vmImageName)
    steps:
    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        containerRegistry: 'aarviaahanaacrdevopsconnection'
        repository: 'tomcat/snakes'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
